# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            '@mdaviesnet Blog'
tagline:          ''
description:      '.NET, Azure, MVC'
url:              http://blog.mdavies.net
baseurl:          /

author:
  name:           'Matt Davies'
  url:            https://twitter.com/mdaviesnet

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/MattDavies/mattdavies.github.io
permalink:    /:year/:month/:day/:title/