title:            '@mdaviesnet Blog'
tagline:          ''
description:      '.NET, Azure, MVC'
url:              http://mdavies.net
baseurl:          /

author:
  name:           'Matt Davies'
  url:            https://twitter.com/mdaviesnet

paginate:         5

permalink:    /:year/:month/:day/:title/

timezone: Australia/Perth